@DataBinding_Controllers_HostAddress = http://localhost:5034

GET {{DataBinding_Controllers_HostAddress}}/w1?count=3
Accept: application/json

###

GET {{DataBinding_Controllers_HostAddress}}/w2
Accept: application/json
Count: 10

###

POST {{DataBinding_Controllers_HostAddress}}/w3
Accept: application/json
Content-Type: application/json

{"Date":"2024-01-01", "TemperatureC": -20}

###

POST {{DataBinding_Controllers_HostAddress}}/w4
Accept: application/json
Content-Type: application/x-www-form-urlencoded

date=2024-06-01&temperatureC=20

###

GET {{DataBinding_Controllers_HostAddress}}/w2-1
Accept: application/json
X-Count: 15

###

POST {{DataBinding_Controllers_HostAddress}}/w4
Accept: application/json
Content-Type: application/x-www-form-urlencoded

data.date=2024-06-01&data.temperatureC=20

###

POST {{DataBinding_Controllers_HostAddress}}/w4-1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

dto.date=2024-06-01&dto.temperatureC=20

###

GET {{DataBinding_Controllers_HostAddress}}/w5?data=10&data=5
# GET {{DataBinding_Controllers_HostAddress}}/w5?data[0]=10&data[1]=5
Accept: application/json

###

POST {{DataBinding_Controllers_HostAddress}}/w6
Accept: application/json
Content-Type: application/x-www-form-urlencoded

data[0].date=2024-06-01&data[0].temperatureC=20&data[1].date=2024-06-02&data[1].temperatureC=30

###

POST {{DataBinding_Controllers_HostAddress}}/w7
Accept: application/json
Content-Type: application/x-www-form-urlencoded

data[0].date=2024-06-01&data[0].temperatureC=20&data[1].date=2024-06-02&data[1].temperatureC=30

###