<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>FluentValidation_Controllers</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);AUTOMATIC</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common-FluentValidation\Common-FluentValidation.csproj" />
    <ProjectReference Include="..\Common-WeatherForecast\Common-WeatherForecast.csproj" />
  </ItemGroup>

</Project>
