<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Autofac_WebApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lct08-AspNetCore-DependencyInjection\Common-WeatherForecast-Simple\Common-WeatherForecast-Simple.csproj" />
  </ItemGroup>

</Project>
